// <auto-generated />
namespace Webdeveloper.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FirstChangeofdboclient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstChangeofdboclient));
        
        string IMigrationMetadata.Id
        {
            get { return "201606210101421_First Change of dbo.client"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
